// <auto-generated />
namespace OTManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DontputnonentityclassmodulesintheModelsfolderyouidiot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DontputnonentityclassmodulesintheModelsfolderyouidiot));
        
        string IMigrationMetadata.Id
        {
            get { return "201704282306239_Don't put non-entity class modules in the Models folder, you idiot."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
