// <auto-generated />
namespace OTManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedconfirmationtoRegistrationentryt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedconfirmationtoRegistrationentryt));
        
        string IMigrationMetadata.Id
        {
            get { return "201705052355575_Added confirmation to Registration entryt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
